fix pipeline

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,89 +29,89 @@ jobs:
           npm --version  
 
       - name: Lint
-      run: npm run lint
+        run: npm run lint
 
-    - name: Build
-      run: npm run build:all
+      - name: Build
+        run: npm run build:all
 
-    - name: Test jest
-      run: npm run test:cov
+      - name: Test jest
+        run: npm run test:cov
 
-    - name: Test cy
-      run: npm run cy:run:cov
+      - name: Test cy
+        run: npm run cy:run:cov
 
-    - name: Merge cov
-      run: npm run cov:merge
+      - name: Merge cov
+        run: npm run cov:merge
 
-    - name: Show coverage
-      run: npm run cov:show
+      - name: Show coverage
+        run: npm run cov:show
 
-    - name: Archive code coverage results
-      uses: actions/upload-artifact@v3
-      with:
-        name: code-coverage-report
-        path: ./reports/coverage-full-total/
+      - name: Archive code coverage results
+        uses: actions/upload-artifact@v3
+        with:
+          name: code-coverage-report
+          path: ./reports/coverage-full-total/
 
-    - name: Comment coverage
-      continue-on-error: true
-      uses: danhunsaker/clover-reporter-action@v0.2.17-clover
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        clover-file: ./reports/coverage-full-total/clover.xml
+      - name: Comment coverage
+        continue-on-error: true
+        uses: danhunsaker/clover-reporter-action@v0.2.17-clover
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          clover-file: ./reports/coverage-full-total/clover.xml
 
-    - name: Monitor coverage
-      continue-on-error: true
-      run: npm run cov:check
+      - name: Monitor coverage
+        continue-on-error: true
+        run: npm run cov:check
 
-    - name: Publish Jest Test Report
-      uses: mikepenz/action-junit-report@v3
-      if: success() || failure() # always run even if the previous step fails
-      with:
-        report_paths: '**/reports/jest/*.xml'
-        check_name: 'Jest Test Report'
-        detailed_summary: true
+      - name: Publish Jest Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/reports/jest/*.xml'
+          check_name: 'Jest Test Report'
+          detailed_summary: true
 
-    - name: Publish
-      if: success()
-      env:
-        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-      run: |
-        branch=${{ github.ref }}
-        echo "Branch: $branch" 
-        
-        gitmsg="${{ github.event.commits[0].message }}"
-        echo "Commit: $gitmsg" 
-        
-        if [[ "$gitmsg" =~ "[patch]" ]]; then
-          echo "publish patch"
-          npm run publish:patch
-          git push --tags
-          exit 0
-        fi 
-        
-        if [[ "$gitmsg" =~ "[fix]" ]]; then
-          echo "publish patch"
-          npm run publish:patch
-          git push --tags
-          exit 0
-        fi
-        
-        if [[ "$gitmsg" =~ "[minor]" ]]; then
-          echo "publish minor"
-          npm run publish:minor
-          git push --tags
-          exit 0
-        fi
-        
-        if [[ "$gitmsg" =~ "[major]" ]]; then
-          echo "publish major"
-          npm run publish:major
-          git push --tags
-          exit 0
-        fi
-        
-        # echo "publishing alpha, for other commit message should contain [minor], [major] or [patch]/[fix]"
-        # npm run publish:alpha
-        # git push --tags    
-
+      - name: Publish
+        if: success()
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: |
+          branch=${{ github.ref }}
+          echo "Branch: $branch" 
+          
+          gitmsg="${{ github.event.commits[0].message }}"
+          echo "Commit: $gitmsg" 
+          
+          if [[ "$gitmsg" =~ "[patch]" ]]; then
+            echo "publish patch"
+            npm run publish:patch
+            git push --tags
+            exit 0
+          fi 
+          
+          if [[ "$gitmsg" =~ "[fix]" ]]; then
+            echo "publish patch"
+            npm run publish:patch
+            git push --tags
+            exit 0
+          fi
+          
+          if [[ "$gitmsg" =~ "[minor]" ]]; then
+            echo "publish minor"
+            npm run publish:minor
+            git push --tags
+            exit 0
+          fi
+          
+          if [[ "$gitmsg" =~ "[major]" ]]; then
+            echo "publish major"
+            npm run publish:major
+            git push --tags
+            exit 0
+          fi
+          
+          # echo "publishing alpha, for other commit message should contain [minor], [major] or [patch]/[fix]"
+          # npm run publish:alpha
+          # git push --tags    
+  
 
